# Generated by Django 4.2.5 on 2023-11-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('puntos', models.IntegerField()),
            ],
        ),
    ]
