# Generated by Django 4.2.5 on 2023-11-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intro', '0002_puntos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Puntos',
        ),
        migrations.AddField(
            model_name='user',
            name='puntos',
            field=models.IntegerField(null=True),
        ),
    ]
